/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Core Brand
        "primary":                   "#091c00",
        "on-primary":                "#ffffff",
        "primary-container":         "#163300",
        "on-primary-container":      "#7a9e5d",
        "primary-fixed":             "#c8eea5",
        "primary-fixed-dim":         "#acd28c",
        "on-primary-fixed":          "#0c2000",
        "on-primary-fixed-variant":  "#304f18",
        "inverse-primary":           "#acd28c",
        // Secondary (Lime Accent)
        "secondary":                 "#2f6c00",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#9FE870",
        "on-secondary-container":    "#163300",
        "secondary-fixed":           "#acf67c",
        "secondary-fixed-dim":       "#91d963",
        "on-secondary-fixed":        "#092100",
        "on-secondary-fixed-variant":"#225100",
        // Tertiary (Deep Teal)
        "tertiary":                  "#00192b",
        "on-tertiary":               "#ffffff",
        "tertiary-container":        "#002f4a",
        "on-tertiary-container":     "#6698c2",
        "tertiary-fixed":            "#cce5ff",
        "tertiary-fixed-dim":        "#99ccf8",
        "on-tertiary-fixed":         "#001e31",
        "on-tertiary-fixed-variant": "#084b71",
        // Surface / Background
        "background":                "#fafaf1",
        "on-background":             "#1a1c17",
        "surface":                   "#fafaf1",
        "surface-dim":               "#dadbd2",
        "surface-bright":            "#fafaf1",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#f4f4ec",
        "surface-container":         "#eeeee6",
        "surface-container-high":    "#e8e9e0",
        "surface-container-highest": "#e3e3db",
        "surface-variant":           "#e3e3db",
        "surface-tint":              "#47672d",
        "on-surface":                "#1a1c17",
        "on-surface-variant":        "#43483d",
        "inverse-surface":           "#2f312c",
        "inverse-on-surface":        "#f1f1e9",
        // Outline
        "outline":                   "#74796c",
        "outline-variant":           "#c3c8b9",
        // Error
        "error":                     "#ba1a1a",
        "on-error":                  "#ffffff",
        "error-container":           "#ffdad6",
        "on-error-container":        "#93000a",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "sm":      "0.5rem",
        "md":      "1.5rem",
        "lg":      "2rem",
        "xl":      "3rem",
        "full":    "9999px",
      },
      spacing: {
        "base":    "4px",
        "xs":      "8px",
        "sm":      "16px",
        "md":      "24px",
        "lg":      "40px",
        "xl":      "64px",
        "section": "100px",
        "hero":    "124px",
      },
      fontFamily: {
        "display-xl": ["Work Sans", "sans-serif"],
        "display-lg": ["Work Sans", "sans-serif"],
        "display-md": ["Work Sans", "sans-serif"],
        "heading-lg": ["Inter", "sans-serif"],
        "body-md":    ["Inter", "sans-serif"],
        "caption":    ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["89px",  { lineHeight: "0.85", letterSpacing: "-0.02em", fontWeight: "900" }],
        "display-lg": ["61px",  { lineHeight: "1",    fontWeight: "900" }],
        "display-md": ["45px",  { lineHeight: "1.1",  fontWeight: "700" }],
        "heading-lg": ["25px",  { lineHeight: "1.25", fontWeight: "700" }],
        "body-md":    ["16px",  { lineHeight: "1.5",  fontWeight: "400" }],
        "caption":    ["12px",  { lineHeight: "1.44", fontWeight: "400" }],
      },
      animation: {
        "spin-slow": "spin 3s linear infinite",
        "pulse-node": "nodeP 2s infinite",
      },
      keyframes: {
        nodeP: {
          "0%":   { transform: "scale(0.95)", boxShadow: "0 0 0 0 rgba(172,246,124,0.7)" },
          "70%":  { transform: "scale(1)",    boxShadow: "0 0 0 10px rgba(172,246,124,0)" },
          "100%": { transform: "scale(0.95)", boxShadow: "0 0 0 0 rgba(172,246,124,0)" },
        },
      },
      boxShadow: {
        "card": "0 6px 20px 0 rgba(0,0,0,0.08)",
        "modal": "0 10px 32px 0 rgba(0,0,0,0.15)",
      },
    },
  },
  plugins: [],
}
