steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_GCR_REGION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/mintflow-backend:$COMMIT_SHA'
      - '.'

  # 2. Push the image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_GCR_REGION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/mintflow-backend:$COMMIT_SHA'

  # 3. Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mintflow-backend'
      - '--image'
      - '$_GCR_REGION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/mintflow-backend:$COMMIT_SHA'
      - '--region'
      - '$_GCR_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - '$_GCR_REGION-docker.pkg.dev/$PROJECT_ID/$_AR_REPO/mintflow-backend:$COMMIT_SHA'

substitutions:
  _GCR_REGION: 'us-central1'
  _AR_REPO: 'mintflow'

options:
  logging: CLOUD_LOGGING_ONLY
